name: Deploy To S3 And Invalidate CloudFront
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기 2
        uses: actions/checkout@v2

      - name: 의존성 설치
        run: |
          npm install

      - name: 빌드하기
        run: |
          npm run build
      - name: AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: S3 기존 파일들 전체 삭제
        run: |
          aws s3 rm --recursive s3://oz-work
