name: Deploy To S3 And Invalidate CloudFront
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기 2
        uses: actions/checkout@v2

      - name: 의존성 설치
        run: |
          npm install

      - name: 빌드하기
        run: |
          npm run build
