name: Github Actions 실행 시켜보기

on:
  push:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World 출력하기
        run: echo "Hello, world!"

      - name: 여러 명렁어 문장 작성하기
        run: |
          echo "첫 번째 명령어 실행"
          echo "두 번째 명령어 실행"
          echo "세 번째 명령어 실행"
          pwd

      - name: Github Actions 자체 저장되어 있는 변수 사용해보기
        run: |
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_SHA}
